<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
/*
implementation of hook_menu().
*/
function xcos_textbook_companion_menu()
{
	$items = array();
	/* users */
	$items['xcos-textbook-companion/add-tbc-titles'] = array(
        'title' => 'Add TBC titles',
        'description' => 'Add TBC titles',
        'page callback' => 'drupal_get_form',
        'page arguments' => array(
            'add_xcos_tbc_titles_form',
        ),
        'access arguments' => array(
            'xcos add tbc titles',
        ),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'add_xcos_tbc_titles.inc',
    );
	$items['xcos-textbook-companion/completed-books'] = array(
		'title' => 'Completed Books',
		'page callback' => 'xcos_completed_books',
		'access arguments' => array(
		'display xcos books in progress'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'display_books.inc'
	);
	$items['xcos-textbook-companion/books-in-progress'] = array(
		'title' => 'Books in progress',
		'page callback' => 'xcos_books_in_progress',
		'access arguments' => array(
		'display xcos books in progress'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'display_books.inc'
	);
	$items['xcos-textbook-companion/proposal'] = array(
		'title' => 'Xcos Book Proposal Form',
		'description' => 'Xcos Book Proposal Form.',
		'page callback' => 'xcos_textbook_companion_proposal_all',
		//'access callback' => 'user_access',
		'access arguments' => array(
			'create xcos book proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'proposal.inc'
	);
	/*$items["aicte_proposal"] = array(
	"title" => "AICTE xcos book proposal",
	"description" => "AICTE xcos book proposal Form",
	"page callback" => "xcos_textbook_companion_aicte_proposal_all",
	'access arguments' => array('create xcos book proposal'),
	'type' => MENU_CALLBACK,
	);*/
	$items["xcos-textbook-companion/all_proposal"] = array(
		"title" => "xcos book proposal",
		"description" => "xcos book proposal Form",
		"page callback" => "xcos_textbook_companion_aicte_proposal_all",
		'access arguments' => array(
			'create xcos book proposal'
		),
		'type' => MENU_CALLBACK
	);
	/* for reviewers */
	$items['xcos-textbook-companion/manage-proposal'] = array(
		'title' => 'Manage xcos book proposals',
		'description' => 'Manage xcos book proposals',
		'page callback' => '_proposal_pending',
		'access callback' => 'user_access',
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/manage-proposal/pending'] = array(
		'title' => 'Pending Proposals',
		'description' => 'Pending Proposals Queue',
		'page callback' => '_proposal_pending',
		'access callback' => 'user_access',
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 1,
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/manage-proposal/all'] = array(
		'title' => 'All Proposals',
		'description' => 'All Proposals',
		'page callback' => '_proposal_all',
		'access callback' => 'user_access',
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 2,
		'file' => 'manage_proposal.inc'
	);
	/*$items['xcos-textbook-companion/manage-proposal/category'] = array(
	'title' => 'Categorize',
	'description' => 'Categorize Books',
	'page callback' => '_category_all',
	'access callback' => 'user_access',
	'access arguments' => array('approve xcos book proposal'),
	'type' => MENU_LOCAL_TASK,
	'weight' => 2,
	'file' => 'manage_proposal.inc',
	);*/
	$items['xcos-textbook-companion/manage-proposal/failed'] = array(
		'title' => 'Failed Proposals',
		'description' => 'Failed to submit code',
		'page callback' => '_failed_all',
		'access callback' => 'user_access',
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 3,
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/manage-proposal/approve'] = array(
		'title' => 'Proposal Approval',
		'description' => 'Proposal Approval',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'proposal_approval_form'
		),
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/manage-proposal/status'] = array(
		'title' => 'Proposal Status',
		'description' => 'Proposal Status',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'proposal_status_form'
		),
		'access arguments' => array(
			'approve xcos book proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/manage-proposal/edit'] = array(
		'title' => 'Edit Proposal',
		'description' => 'Edit Proposal',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'proposal_edit_form'
		),
		'access arguments' => array(
			'edit xcos book proposal'
		),
		'type' => MENU_CALLBACK,
		'file' => 'manage_proposal.inc'
	);
	/*$items['xcos-textbook-companion/manage-proposal/category/edit'] = array(
	'title' => 'Edit Category',
	'description' => 'Edit category',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('category_edit_form'),
	'access arguments' => array('edit xcos book proposal'),
	'type' => MENU_CALLBACK,
	'file' => 'manage_proposal.inc',
	);*/
	$items['xcos-textbook-companion/code-approval'] = array(
		'title' => 'Manage Xcos Code Approval',
		'description' => 'Manage Xcos Code Approval',
		'page callback' => 'code_approval',
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'code_approval.inc'
	);
	$items['xcos-textbook-companion/code-approval/approve'] = array(
		'title' => 'Code Approval',
		'description' => 'Code Approval',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'code_approval_form'
		),
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 1,
		'file' => 'code_approval.inc'
	);
	$items['xcos-textbook-companion/code-approval/bulk'] = array(
		'title' => 'Bulk Manage',
		'description' => 'Bulk Mangage',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'bulk_approval_form'
		),
		'access arguments' => array(
			'bulk manage xcos code'
		),
		'type' => MENU_LOCAL_TASK,
		'weight' => 3,
		'file' => 'code_approval.inc'
	);
	/* $items['xcos-textbook-companion/code-approval/edit-code-submission'] = array(
	'title' => 'Edit Code Submission',
	'description' => 'Enable users code submission interface',
	// 'page callback' => 'drupal_get_form',
	'page callback' => 'edit_code_submission',
	// 'page arguments' => array(
	//     'edit_code_submission_form'
	//  ),
	'access arguments' => array(
	'bulk manage xcos code'
	),
	'type' => MENU_LOCAL_TASK,
	'weight' => 3,
	'file' => 'code_approval.inc'
	);*/
	$items['xcos-textbook-companion/code-approval/edit-code-submission/edit'] = array(
		'title' => 'Edit Code Submission',
		'description' => 'Enable users code submission interface',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'edit_code_submission_form'
		),
		'access arguments' => array(
			'bulk manage xcos code'
		),
		'file' => 'code_approval.inc'
	);
	$items['xcos-textbook-companion/code-approval/editcode'] = array(
		'title' => 'Admin Edit Example',
		'description' => 'Admin Edit Example',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'upload_examples_admin_edit_form'
		),
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_CALLBACK,
		'weight' => 3,
		'file' => 'editcodeadmin.inc'
	);
	$items['xcos-textbook-companion/code-approval/notes'] = array(
		'title' => 'Notes for Reviewers',
		'description' => 'Notes for Reviewers',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'book_notes_form'
		),
		'access arguments' => array(
			'bulk manage xcos code'
		),
		'type' => MENU_CALLBACK,
		'weight' => 4,
		'file' => 'notes.inc'
	);
	/* $items['code_approval/dependency'] = array(
	'title' => 'Dependency',
	'description' => 'Dependency',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('xcos_textbook_companion_dependency_approval_form'),
	'access arguments' => array('bulk manage xcos code'),
	'type' => MENU_LOCAL_TASK,
	'weight' => 3,
	'file' => 'dependency_approval.inc',
	);*/
	$items['xcos-textbook-companion/code'] = array(
		'title' => 'Xcos Code Submission',
		'description' => 'Xcos Code Submission',
		'page callback' => 'list_chapters',
		'access callback' => 'user_access',
		'access arguments' => array(
			'upload xcos code'
		),
		'file' => 'general.inc'
	);
	$items['xcos-textbook-companion/code/list_chapters'] = array(
		'title' => 'List Chapters',
		'description' => 'List Chapters',
		'page callback' => 'list_chapters',
		'access arguments' => array(
			'upload xcos code'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'file' => 'general.inc',
		'weight' => 1
	);
	$items['xcos-textbook-companion/code/upload'] = array(
		'title' => 'Code Submission',
		'description' => 'Code Submission',
		'page callback' => 'upload_examples',
		'access arguments' => array(
			'upload xcos code'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'code.inc',
		'weight' => 2
	);
	$items['xcos-textbook-companion/code/upload-dep'] = array(
	'title' => 'Upload Dependency',
	'description' => 'Upload Dependency Files',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('upload_dependency_form'),
	'access arguments' => array('upload xcos code'),
	'type' => MENU_LOCAL_TASK,
	'file' => 'dependency.inc',
	'weight' => 3,
	);
	$items['xcos-textbook-companion/code/edit-dep'] = array(
	'title' => 'Edit Dependency',
	'description' => 'Edit Dependency File',
	'page callback' => 'edit_dependency',
	'access arguments' => array('upload xcos code'),
	'type' => MENU_CALLBACK,
	'file' => 'dependency.inc',
	);
	$items['xcos-textbook-companion/code/delete-dep'] = array(
	'title' => 'Delete Dependency',
	'description' => 'Delete Dependency File',
	'page callback' => 'delete_dependency',
	'access arguments' => array('upload xcos code'),
	'type' => MENU_CALLBACK,
	'file' => 'dependency.inc',
	);
	$items['xcos-textbook-companion/code/edit'] = array(
		'title' => 'Edit Example',
		'description' => 'Edit Example',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'upload_examples_edit_form'
		),
		'access arguments' => array(
			'edit uploaded xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'editcode.inc'
	);
	$items['xcos-textbook-companion/code/delete'] = array(
		'title' => 'Delete Example',
		'description' => 'Delete Example',
		'page callback' => '_upload_examples_delete',
		'access arguments' => array(
			'upload xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'code.inc'
	);
	$items['xcos-textbook-companion/code/chapter/edit'] = array(
		'title' => 'Edit Chapter Title',
		'description' => 'Edit Chapter Title',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'edit_chapter_title_form'
		),
		'access arguments' => array(
			'upload xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'editcode.inc'
	);
	$items['xcos-textbook-companion/code/list-examples'] = array(
		'title' => 'List Examples',
		'description' => 'List Examples',
		'page callback' => 'list_examples',
		'access arguments' => array(
			'upload xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'general.inc',
		'weight' => 3
	);
	$items['xcos-textbook-companion/textbook-search'] = array(
		'title' => 'Book Search',
		'description' => '',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_search_form'
		),
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'search.inc'
	);
	$items['xcos-textbook-companion/textbook-search/search'] = array(
		'title' => 'Book Search',
		'description' => '',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_search_form'
		),
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'file' => 'search.inc',
		'weight' => 1
	);
	$items['xcos-textbook-companion/textbook-search/book'] = array(
		'title' => 'By Book Title',
		'description' => '',
		'page callback' => 'xcos_textbook_companion_browse_book',
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'search.inc',
		'weight' => 2
	);
	$items['xcos-textbook-companion/textbook-search/author'] = array(
		'title' => 'By Author',
		'description' => '',
		'page callback' => 'xcos_textbook_companion_browse_author',
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'search.inc',
		'weight' => 3
	);
	$items['xcos-textbook-companion/textbook-search/college'] = array(
		'title' => 'By College',
		'description' => '',
		'page callback' => 'xcos_textbook_companion_browse_college',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_browse_college_form'
		),
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'search.inc',
		'weight' => 4
	);
	$items['xcos-textbook-companion/textbook-search/student'] = array(
		'title' => 'By Student',
		'description' => '',
		'page callback' => 'xcos_textbook_companion_browse_student',
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'search.inc',
		'weight' => 5
	);
	/* $items['textbook_run'] = array(
	'title' => 'Download Codes',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('xcos_textbook_companion_run_form_ajax'),
	'access arguments' => array('access xcos content'),
	'type' => MENU_NORMAL_ITEM,
	'file' => 'run.inc',
	);*/
	$items['xcos-textbook-companion/textbook-run'] = array(
		'title' => 'Download Codes',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_run_form'
		),
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'run.inc'
	);
	/*$items['textbook_run_ajax'] = array(
	'page callback' => 'textbook_run_ajax',
	'access callback' => TRUE,
	'file' => 'run.inc',
	);*/
	/*$items['download_codes'] = array(
	'title' => 'Download Codes',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('xcos_textbook_companion_run_form_ajax'),
	'access arguments' => array('access xcos content'),
	'type' => MENU_NORMAL_ITEM,
	'file' => 'run.inc',
	);*/
	$items['xcos-textbook-companion/download-codes'] = array(
		'title' => 'Download Codes',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_run_form'
		),
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'run.inc'
	);
	/* download callbacks */
	$items['xcos-textbook-companion/download/file'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_example_file',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['xcos-textbook-companion/download/samplecode'] = array(
		'title' => 'Sample Code Download',
		'description' => 'Sample Code Download',
		'page callback' => 'xcos_textbook_companion_download_sample_code',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['xcos-textbook-companion/download/dependency'] = array(
	'title' => 'Code Download',
	'description' => 'Code Download', 
	'page callback' => 'xcos_textbook_companion_download_dependency_file',
	'access arguments' => array('download xcos code'),
	'type' => MENU_CALLBACK,
	'file' => 'download.inc',
	);
	$items['xcos-textbook-companion/download/example'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_example',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['xcos-textbook-companion/download/codable-example'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_codable_example_file',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['xcos-textbook-companion/download/chapter'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_chapter',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	$items['xcos-textbook-companion/download/book'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_book',
		'access arguments' => array(
			'download xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'download.inc'
	);
	/* reviewer download */
	$items['xcos-textbook-companion/full-download/chapter'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_full_chapter',
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	$items['xcos-textbook-companion/full-download/book'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_full_book',
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	/* external reviewer download */
	$items['xcos-textbook-companion/full-download-external/chapter'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_full_chapter',
		'access arguments' => array(
			'download xcos books to review'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	$items['xcos-textbook-companion/full-download-external/book'] = array(
		'title' => 'Code Download',
		'description' => 'Code Download',
		'page callback' => 'xcos_textbook_companion_download_full_book',
		'access arguments' => array(
			'download xcos books to review'
		),
		'type' => MENU_CALLBACK,
		'file' => 'full_download.inc'
	);
	/* latex script for book generation */
	$items['xcos-textbook-companion/generate-book'] = array(
		'title' => 'Generate Book',
		'description' => 'Generate Book From Latex Script',
		'page callback' => 'xcos_textbook_companion_download_book',
		'access arguments' => array(
			'generate xcos book'
		),
		'type' => MENU_CALLBACK,
		'file' => 'latex.inc'
	);
	$items['xcos-textbook-companion/delete-book'] = array(
		'title' => 'Delete Book PDF',
		'description' => 'Delete Book PDF',
		'page callback' => 'xcos_textbook_companion_delete_book',
		'access arguments' => array(
			'approve xcos code'
		),
		'type' => MENU_CALLBACK,
		'file' => 'latex.inc'
	);
	/* general purpose callbacks */
	$items['xcos-textbook-companion/ajax'] = array(
		'title' => 'Ajax',
		'description' => 'Ajax',
		'page callback' => 'xcos_textbook_companion_ajax',
		'access arguments' => array(
			'access xcos content'
		),
		'type' => MENU_CALLBACK
	);
	/* for admin */
	$items['admin/settings/xcos-tbc'] = array(
		'title' => 'Xcos Book Companion Settings',
		'description' => 'Xcos Textbook Companion Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'xcos_textbook_companion_settings_form'
		),
		'access arguments' => array(
			'administer xcos book companion'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'settings.inc'
	);
	/* for data entry */
	$items['xcos-textbook-companion/dataentry-book'] = array(
		'title' => 'Approved books list',
		'page callback' => '_data_entry_proposal_all',
		'access callback' => 'user_access',
		'access arguments' => array(
			'dataentry xcos book proposal'
		),
		'file' => 'manage_proposal.inc'
	);
	$items['xcos-textbook-companion/dataentry-edit'] = array(
		'title' => 'Edit book details',
		'page callback' => 'dataentry_edit',
		'access callback' => 'user_access',
		'access arguments' => array(
			'dataentry xcos book proposal'
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'manage_proposal.inc'
	);
	/*Cheque Details and Contact Form */
	$items['xcos-textbook-companion/cheque-manage/all'] = array(
		'title' => 'Cheque Proposals',
		'description' => 'Cheque Proposals',
		'page callback' => 'cheque_proposal_all',
		'access arguments' => array(
			'cheque proposal'
		),
		'file' => 'cheque_manage.inc'
	);
	$items['xcos-textbook-companion/mycontact'] = array(
		'title' => 'Update Contact Details',
		'description' => 'Update Contact Details',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'contact_details'
		),
		'access arguments' => array(
			'contact_details'
		),
		'file' => 'cheque_contact.inc'
	);
	$items['xcos-textbook-companion/cheque-contct'] = array(
		'title' => 'Report',
		'description' => 'Cheque Contact Form',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'cheque_contct_form'
		),
		'access arguments' => array(
			'cheque contct form'
		),
		'file' => 'cheque_contact.inc'
	);
	$items['xcos-textbook-companion/cheque-contact/status'] = array(
		'title' => 'Cheque Status',
		'description' => 'Cheque Status',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'cheque_status_form'
		),
		'access' => 'user_is_logged_in',
		'access arguments' => array(
			'cheque status form'
		),
		'file' => 'cheque_contact.inc'
	);
	$items['xcos-textbook-companion/cheque-contct/report'] = array(
		'title' => 'Report',
		'description' => 'Report',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'cheque_report_form'
		),
		'access' => 'user_is_logged_in',
		'access arguments' => array(
			'cheque report form'
		),
		'file' => 'cheque_contact.inc'
	);
	$items['xcos-textbook-companion/certificate'] = array(
		'title' => 'List Of All Certificates',
		'description' => 'List Of All Certificates',
		'page callback' => '_list_all_certificates',
		'access arguments' => array(
			'list all xcos certificates'
		),
		'file' => 'pdf/list_all_certificates.inc'
	);
	$items['xcos-textbook-companion/certificate/generate-pdf'] = array(
		'title' => 'Download Certificate',
		'description' => 'Download Certificate',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'generate_pdf'
		),
		'access arguments' => array(
			'generate pdf'
		),
		'file' => 'pdf/generate_pdf.inc'
	);
	$items["xcos-textbook-companion/certificates/verify"] = array(
        "title" => "Certificate Verification",
        "page callback" => "verify_certificates",
        "access arguments" => array(
            "verify xcos certificates"
        ),
	'file' => 'pdf/verify_certificates.inc',
       
    );
	$items['xcos-textbook-companion/manage-proposal/paper-submission'] = array(
		'title' => 'Application Submission',
		'description' => 'Application Submission',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'paper_submission_form'
		),
		'access arguments' => array(
			'paper submission form'
		),
		'type' => MENU_CALLBACK,
		'file' => 'cheque_contact.inc'
	);
	$items["xcos-textbook-companion/nonaicte-proposal"] = array(
		"title" => "Book Suggestion Form ",
		"description" => "NON-AICTE xcos book proposal Form",
		'page callback' => 'xcos_textbook_companion_nonaicte_proposal_all',
		'access arguments' => array(
			'create xcos book proposal'
		),
		'type' => MENU_CALLBACK
	);
	return $items;
}
/**
 * Implementation of hook_perm().
 */
function xcos_textbook_companion_permission()
{
	return array(
		'xcos add tbc titles' => array(
            'title' => t('xcos add tbc titles'),
            'restrict access' => true,
        ),
		"create xcos book proposal" => array(
			"title" => t("xcos book proposal Form"),
			"description" => t("xcos book proposal Form.")
		),
		"approve xcos book proposal" => array(
			"title" => t("Approve xcos book proposal"),
			"description" => t("Allows users to approve xcos book proposal.")
		),
		"approve xcos code" => array(
			"title" => t("approve xcos code"),
			"description" => t("Allows users to approve xcos code.")
		),
		"upload xcos code" => array(
			"title" => t("upload xcos code"),
			"description" => t("Allows users to upload xcos code.")
		),
		"edit uploaded xcos code" => array(
			"title" => t("edit uploaded xcos code"),
			"description" => t("Allows users to edit uploaded xcos code.")
		),
		"download xcos code" => array(
			"title" => t("Download code"),
			"description" => t("Allows users to download xcos code.")
		),
		"create feedback" => array(
			"title" => t("Create feedback"),
			"description" => t("Allows users to create feedback.")
		),
		"bulk manage xcos code" => array(
			"title" => t("bulk manage xcos code"),
			"description" => t("Allows users to manage Bulk code.")
		),
		"bulk delete xcos code" => array(
			"title" => t("Bulk delete xcos code"),
			"description" => t("Allows users to delete bulk code.")
		),
		"edit xcos book proposal" => array(
			"title" => t("Edit xcos book proposal"),
			"description" => t("Allows users to edit xcos book proposal.")
		),
		"administer xcos book companion" => array(
			"title" => t("Administer book companion"),
			"description" => t("Allows users to administer xcos book companion.")
		),
		"generate xcos book" => array(
			"title" => t("Generate book"),
			"description" => t("Allows users to generate xcos book.")
		),
		"cheque contct form" => array(
			"title" => t("Cheque contact form"),
			"description" => t("Cheque contct form.")
		),
		"contact_details" => array(
			"title" => t("Contact_details"),
			"description" => t("Contact_details.")
		),
		"comment cheque" => array(
			"title" => t("Comment cheque"),
			"description" => t("Comment cheque.")
		),
		"list all xcos certificates" => array(
			"title" => t("list all xcos certificates"),
			"description" => t("Allows users to list all xcos certificates.")
		),
		"verify xcos certificates" => array(
			"title" => t("Verify certificates"),
			"description" => t("Allows users to verify xcos certificates.")
		),
		"generate pdf" => array(
			"title" => t("Generate pdf"),
			"description" => t("Allows users to Generate pdf.")
		),
		"paper submission form" => array(
			"title" => t("paper submission form"),
			"description" => t("Paper submission form.")
		),
		"cheque status form" => array(
			"title" => t("Cheque status form"),
			"description" => t("Cheque status form.")
		),
		"cheque report form" => array(
			"title" => t("Cheque report form"),
			"description" => t("Cheque report form.")
		),
		"cheque proposal" => array(
			"title" => t("Cheque proposal"),
			"description" => t("Cheque proposal.")
		),
		"download xcos books to review" => array(
			"title" => t("download xcos books to review"),
			"description" => t("Download books to review.")
		),
		"display xcos books in progress" => array(
			"title" => t("Book display xcos books in progress"),
			"description" => t("display xcos books in progress.")
		),
		"access xcos content" => array(
			"title" => t("access xcos content"),
			"description" => t("access xcos content")
		),
	);
}
function xcos_textbook_companion_aicte_proposal_all()
{
	global $user;
	$page_content = "";
	if (!$user->uid)
	{
		/*$query = "
		SELECT * FROM xcos_textbook_companion_aicte
		WHERE status = 0
		";
		$result = db_query($query);*/
		$query = db_select('xcos_textbook_companion_aicte');
		$query->fields('xcos_textbook_companion_aicte');
		$query->condition('status', 0);
		$result = $query->execute();
		$page_content .= "<ul>";
		$page_content .= "<li>These are the list of books available for <em>Textbook Companion</em> proposal.</li>";
		$page_content .= "<li>Please <a href='/user'><b><u>Login</u></b></a> to create a proposal.</li>";
		$page_content .= "</ul>";
		$page_content .= "Search :  <input type='text' id='searchtext' style='width:82%'/>";
		$page_content .= "<input type='button' value ='clear' id='search_clear'/>";
		$page_content .= "<div id='aicte-list-wrapper'>";
		$num_rows = $result->rowCount();
		if ($num_rows > 0)
		{
			$i = 1;
			while ($row = $result->fetchObject())
			{
				/* fixing title string */
				$title = "";
				$edition = "";
				$year = "";
				$title = "{$row->book} by {$row->author}";
				if ($row->edition)
				{
					$edition = "<i>ed</i>: {$row->edition}";
				} //$row->edition
				if ($row->year)
				{
					if ($row->edition)
					{
						$year = ", <i>pub</i>: {$row->year}";
					} //$row->edition
					else
					{
						$year = "<i>pub</i>: {$row->year}";
					}
				} //$row->year
				if ($edition or $year)
				{
					$title .= "({$edition} {$year})";
				} //$edition or $year
				$page_content .= "<div class='title'>{$i}) {$title}</div>";
				$i++;
			} //$row = $result->fetchObject()
		} //$num_rows > 0
		$page_content .= "</div>";
		/* adding aicte report form */
		//$page_content .= drupal_get_form("xcos_textbook_companion_aicte_report_form");
		return $page_content;
	} //!$user->uid
	/* check if user has already submitted a proposal */
	/* $proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE uid = %d ORDER BY id DESC LIMIT 1", $user->uid);*/
	$query = db_select('xcos_textbook_companion_proposal');
	$query->fields('xcos_textbook_companion_proposal');
	$query->condition('uid', $user->uid);
	$query->orderBy('id', 'DESC');
	$query->range(0, 1);
	$proposal_q = $query->execute();
	if ($proposal_q)
	{
		if ($proposal_data = $proposal_q->fetchObject())
		{
			switch ($proposal_data->proposal_status)
			{
				case 0:
					drupal_set_message(t('We have already received your proposal. We will get back to you soon.'), 'status');
					drupal_goto('');
					return;
					break;
				case 1:
					drupal_set_message(t('Your proposal has been approved. Please go to ' . l('Code Submission', 'xcos-textbook-companion/code') . ' to upload your code'), 'status');
					drupal_goto('');
					return;
					break;
				case 2:
					drupal_set_message(t('Your proposal has been disapproved. Please create another proposal below.'), 'error');
					break;
				case 3:
					drupal_set_message(t('Congratulations! You have completed your last xcos book proposal. You can create another proposal below.'), 'status');
					break;
				default:
					drupal_set_message(t('Invalid proposal state. Please contact site administrator for further information.'), 'error');
					drupal_goto('');
					return;
					break;
			} //$proposal_data->proposal_status
		} //$proposal_data = $proposal_q->fetchObject()
	} //$proposal_q
	variable_del("aicte_" . $user->uid);
	$page_content .= "<h5><b>* Please select any 3 books from the below list.</b></h5></br>";
	$page_content .= "Search :  <input type='text' id='searchtext' style='width:82%'/>";
	$page_content .= "<input type='button' value ='clear' id='search_clear'/>";
	//$page_content .= drupal_get_form("xcos_textbook_companion_aicte_report_form");
	$xcos_textbook_companion_aicte_proposal_form = drupal_get_form("xcos_textbook_companion_aicte_proposal_form");
	$page_content .= drupal_render($xcos_textbook_companion_aicte_proposal_form);
	return $page_content;
}
/*non aicte xcos book proposal */
function xcos_textbook_companion_nonaicte_proposal_all()
{
	global $user;
	$page_content = "";
	if (!$user->uid)
	{
		$page_content .= "<ul>";
		$page_content .= "<li>Please <a href='/user'><b><u>Login</u></b></a> to create a proposal.</li>";
		$page_content .= "</ul>";
		return $page_content;
	} //!$user->uid
	/* check if user has already submitted a proposal */
	/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE uid = %d ORDER BY id DESC LIMIT 1", $user->uid);*/
	$query = db_select('xcos_textbook_companion_proposal');
	$query->fields('xcos_textbook_companion_proposal');
	$query->condition('uid', $user->uid);
	$query->orderBy('id', 'DESC');
	$query->range(0, 1);
	$proposal_q = $query->execute();
	if ($proposal_q)
	{
		if ($proposal_data = $proposal_q->fetchObject())
		{
			switch ($proposal_data->proposal_status)
			{
				case 0:
					drupal_set_message(t('We have already received your proposal. We will get back to you soon.'), 'status');
					drupal_goto('');
					return;
					break;
				case 1:
					drupal_set_message(t('Your proposal has been approved. Please go to ' . l('Code Submission', 'xcos-textbook-companion/code') . ' to upload your code'), 'status');
					drupal_goto('');
					return;
					break;
				case 2:
					drupal_set_message(t('Your proposal has been dis-approved. Please create another proposal below.'), 'error');
					break;
				case 3:
					drupal_set_message(t('Congratulations! You have completed your last xcos book proposal. You can create another proposal below.'), 'status');
					break;
				case 5:
					drupal_set_message(t('You have submitted your all codes.'), 'status');
					drupal_goto('');
					return;
					break;
				default:
					drupal_set_message(t('Invalid proposal state. Please contact site administrator for further information.'), 'error');
					drupal_goto('');
					return;
					break;
			} //$proposal_data->proposal_status
		} //$proposal_data = $proposal_q->fetchObject()
	} //$proposal_q
	//variable_del("aicte_".$user->uid);
	$book_proposal_nonaicte_form = drupal_get_form("book_proposal_nonaicte_form");
	$page_content .= drupal_render($book_proposal_nonaicte_form);
	return $page_content;
}
/**
 * Implementation of hook_mail().
 */
function xcos_textbook_companion_mail($key, &$message, $params)
{
	global $user;
	// $language = $message['lianguage'];
	
	$tbc_bcc_emails = array(
		'Bcc' => variable_get('xcos_textbook_companion_emails', '')
	);
	switch ($key)
	{
		case 'proposal_received':

			/* initializing data */
			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_received']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['proposal_received']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$samplecodefilename = "";
			if (strlen($proposal_data->samplefilepath) >= 5)
			{
				$samplecodefilename = substr($proposal_data->samplefilepath, strrpos($proposal_data->samplefilepath, '/') + 1);
			} //strlen($proposal_data->samplefilepath) >= 5
			else
			{
				$samplecodefilename = "Not provided";
			}
			/*$preference1_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND pref_number = %d LIMIT 1", $params['proposal_received']['proposal_id'], 1);
			$preference1_data = db_fetch_object($preference1_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_received']['proposal_id']);
			$query->condition('pref_number', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$preference1_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_received']['proposal_id']);
			$query->condition('pref_number', 2);
			$query->range(0, 1);
			$result = $query->execute();
			$preference2_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_received']['proposal_id']);
			$query->condition('pref_number', 3);
			$query->range(0, 1);
			$result = $query->execute();
			$preference3_data = $result->fetchObject();
			$user_data = user_load($params['proposal_received']['user_id']);
			$message['headers'] = $params['proposal_received']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your textbook companion xcos book proposal has been received', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

This is to inform you that we have received your proposal for Xcos Textbook Companion (TBC) with the following details:

Full Name: ' . $proposal_data->full_name . '
Email: ' . $user_data->mail . '
Mobile: ' . $proposal_data->mobile . '
Department/Branch: ' . $proposal_data->branch . '
University/Institute: ' . $proposal_data->university . '
City: ' . $proposal_data->city . '
State: ' . $proposal_data->state . '
Expected date of completion: ' . date('d-m-Y', $proposal_data->completion_date) . '

Book Preference:-
Title of the book: ' . $preference1_data->book . '
Author name: ' . $preference1_data->author . '
ISBN No.: ' . $preference1_data->isbn . '
Publisher and Place: ' . $preference1_data->publisher . '
Edition: ' . $preference1_data->edition . '
Year of publication: ' . $preference1_data->year . '

Your proposal is under review. You will soon receive an email when your proposal has been approved/ disapproved. Thank you for your submission.    

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'proposal_disapproved':

			/* initializing data */
			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_disapproved']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['proposal_disapproved']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			/*$preference1_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND pref_number = %d LIMIT 1", $params['proposal_disapproved']['proposal_id'], 1);
			$preference1_data = db_fetch_object($preference1_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_disapproved']['proposal_id']);
			$query->condition('pref_number', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$preference1_data = $result->fetchObject();
			$user_data = user_load($params['proposal_disapproved']['user_id']);
			$message['headers'] = $params['proposal_disapproved']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your textbook companion xcos book proposal has been disapproved', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We regret to inform you that your xcos book proposal for Xcos Textbook Companion (TBC) has been disapproved due to following reason. 

Title of the book: ' . $preference1_data->book . '
Reason for disapproval: ' . $proposal_data->message . '

Please try to re-submit it after incorporating the comments given above. Please note that the records for this xcos book proposal have been deleted so that you can submit the proposal again.

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'proposal_approved':
		
			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_approved']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['proposal_approved']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			/* $approved_preference_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND approval_status = 1 LIMIT 1", $params['proposal_approved']['proposal_id']);
			$approved_preference_data = db_fetch_object($approved_preference_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_approved']['proposal_id']);
			$query->condition('approval_status', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$preference1_data = $result->fetchObject();
			$user_data = user_load($params['proposal_approved']['user_id']);
			$message['headers'] = $params['proposal_approved']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your xcos book proposal has been approved', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

Your following book proposal has been approved: 

Full Name: ' . $proposal_data->full_name . '
Email: ' . $user_data->mail . '
Mobile: ' . $proposal_data->mobile . '
Department/Branch: ' . $proposal_data->branch . '
University/Institute: ' . $proposal_data->university . '
City: ' . $proposal_data->city . '
State: ' . $proposal_data->state . '
Expected date of completion: ' . date('d-m-Y', $proposal_data->completion_date) . '

Book Preference:-
Title of the book: ' . $preference1_data->book . '
Author name: ' . $preference1_data->author . '
ISBN No.: ' . $preference1_data->isbn . '
Publisher and Place: ' . $preference1_data->publisher . '
Edition: ' . $preference1_data->edition . '
Year of publication: ' . $preference1_data->year . '

Click on the link given below for the further procedure: https://scilab.in/xcos-textbook-companion/procedure

Please contact us by sending an email to textbook@scilab.in in case you wish to cancel this book proposal.

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'proposal_completed':
			
			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_completed']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['proposal_completed']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			/*$approved_preference_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND approval_status = 1 LIMIT 1", $params['proposal_completed']['proposal_id']);
			$approved_preference_data = db_fetch_object($approved_preference_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['proposal_completed']['proposal_id']);
			$query->condition('approval_status', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$approved_preference_data = $result->fetchObject();
			$user_data = user_load($params['proposal_completed']['user_id']);
			$message['headers'] = $params['proposal_completed']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Congratulations on the completion of the Textbook Companion.', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

The textbook companion on the following book has been completed successfully by you:

Full Name: ' . $proposal_data->full_name . '
Email: ' . $user_data->mail . '
Mobile: ' . $proposal_data->mobile . '
Department/Branch: ' . $proposal_data->branch . '
University/Institute: ' . $proposal_data->university . '
College Teacher / Professor: ' . $proposal_data->faculty . '
Reviewer: ' . $proposal_data->reviewer . '
Expected date of completion: ' . date('d-m-Y', $proposal_data->completion_date) . '
Title of the book: ' . $approved_preference_data->book . '
Author name: ' . $approved_preference_data->author . '
ISBN No.: ' . $approved_preference_data->isbn . '
Publisher and Place: ' . $approved_preference_data->publisher . '
Edition: ' . $approved_preference_data->edition . '
Year of publication: ' . $approved_preference_data->year . '

Your book is now available at following link to download at https://scilab.in/xcos-textbook-companion/completed-books' . '

Now you should be able to propose a new book.

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		/***********************************************************************************************/
		case 'all_code_submitted':
			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_completed']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['all_code_submitted']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			/*$approved_preference_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND approval_status = 1 LIMIT 1", $params['proposal_completed']['proposal_id']);
			$approved_preference_data = db_fetch_object($approved_preference_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['all_code_submitted']['proposal_id']);
			$query->condition('approval_status', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$approved_preference_data = $result->fetchObject();
			$user_data = user_load($params['all_code_submitted']['user_id']);
			$message['headers'] = $params['all_code_submitted']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] You have marked that you have submitted the code for all examples.', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

You have submitted codes for all examples:

Full Name: ' . $proposal_data->full_name . '
Email: ' . $user_data->mail . '
Mobile: ' . $proposal_data->mobile . '
Department/Branch: ' . $proposal_data->branch . '
University/Institute: ' . $proposal_data->university . '
College Teacher / Professor: ' . $proposal_data->faculty . '
Reviewer: ' . $proposal_data->reviewer . '
Expected date of completion: ' . date('d-m-Y', $proposal_data->completion_date) . '


Title of the book: ' . $approved_preference_data->book . '
Author name: ' . $approved_preference_data->author . '
ISBN No.: ' . $approved_preference_data->isbn . '
Publisher and Place: ' . $approved_preference_data->publisher . '
Edition: ' . $approved_preference_data->edition . '
Year of publication: ' . $approved_preference_data->year . '

You shall be notified after the code is reviewed.

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'all_code_submitted_status_changed':

			/*$proposal_q = db_query("SELECT * FROM {xcos_textbook_companion_proposal} WHERE id = %d LIMIT 1", $params['proposal_completed']['proposal_id']);
			$proposal_data = db_fetch_object($proposal_q);*/
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $params['all_code_submitted_status_changed']['proposal_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			/*$approved_preference_q = db_query("SELECT * FROM {xcos_textbook_companion_preference} WHERE proposal_id = %d AND approval_status = 1 LIMIT 1", $params['proposal_completed']['proposal_id']);
			$approved_preference_data = db_fetch_object($approved_preference_q);*/
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('proposal_id', $params['all_code_submitted_status_changed']['proposal_id']);
			$query->condition('approval_status', 1);
			$query->range(0, 1);
			$result = $query->execute();
			$approved_preference_data = $result->fetchObject();
			$user_data = user_load($params['all_code_submitted_status_changed']['user_id']);
			$message['headers'] = $params['all_code_submitted_status_changed']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your interface for code submission has been enabled by the reviewer', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

Your interface for code submission has been enabled by the reviewer, you can now send more code for this book.

Full Name: ' . $proposal_data->full_name . '
Email: ' . $user_data->mail . '
Mobile: ' . $proposal_data->mobile . '
Department/Branch: ' . $proposal_data->branch . '
University/Institute: ' . $proposal_data->university . '
College Teacher / Professor: ' . $proposal_data->faculty . '
Reviewer: ' . $proposal_data->reviewer . '
Expected date of completion: ' . date('d-m-Y', $proposal_data->completion_date) . '


Title of the book: ' . $approved_preference_data->book . '
Author name: ' . $approved_preference_data->author . '
ISBN No.: ' . $approved_preference_data->isbn . '
Publisher and Place: ' . $approved_preference_data->publisher . '
Edition: ' . $approved_preference_data->edition . '
Year of publication: ' . $approved_preference_data->year . '
 
Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		/*****************************************************************************************/
		case 'example_uploaded':

			/*$example_q = db_query("SELECT * FROM {xcos_textbook_companion_example} WHERE id = %d LIMIT 1", $params['example_uploaded']['example_id']);
			$example_data = db_fetch_object($example_q);*/
			$query = db_select('xcos_textbook_companion_example');
			$query->fields('xcos_textbook_companion_example');
			$query->condition('id', $params['example_uploaded']['example_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$example_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $example_data->chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $chapter_data->preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$user_data = user_load($params['example_uploaded']['user_id']);
			$message['headers'] = $params['example_uploaded']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] You have uploaded example for Textbook Companion', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

You have uploaded the following solution :

Title of the book: ' . $preference_data->book . '
Title of the chapter: ' . $chapter_data->name . '
Example number: ' . $example_data->number . '
Caption: ' . $example_data->caption . '

You shall be notified after the solution is reviewed

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'example_updated':
			/*$example_q = db_query("SELECT * FROM {xcos_textbook_companion_example} WHERE id = %d LIMIT 1", $params['example_updated']['example_id']);
			$example_data = db_fetch_object($example_q);*/
			$query = db_select('xcos_textbook_companion_example');
			$query->fields('xcos_textbook_companion_example');
			$query->condition('id', $params['example_updated']['example_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$example_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $example_data->chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $chapter_data->preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$user_data = user_load($params['example_updated']['user_id']);
			$message['headers'] = $params['example_updated']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] You have updated example for Textbook Companion', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

You have updated the following example:

Title of the book: ' . $preference_data->book . '
Title of the chapter: ' . $chapter_data->name . '
Example number: ' . $example_data->number . '
Caption: ' . $example_data->caption . '

The example is still under review. You will be notified when it has been approved.

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'example_updated_admin':
			/*$example_q = db_query("SELECT * FROM {xcos_textbook_companion_example} WHERE id = %d LIMIT 1", $params['example_updated_admin']['example_id']);
			$example_data = db_fetch_object($example_q);*/
			$query = db_select('xcos_textbook_companion_example');
			$query->fields('xcos_textbook_companion_example');
			$query->condition('id', $params['example_updated_admin']['example_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$example_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $example_data->chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $chapter_data->preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$user_data = user_load($params['example_updated_admin']['user_id']);
			$message['headers'] = $params['example_updated_admin']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Reviewer have updated example for Textbook Companion ', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

Reviewer have updated the following example:

Title of the book: ' . $preference_data->book . '
Title of the chapter: ' . $chapter_data->name . '
Example number: ' . $example_data->number . '
Caption: ' . $example_data->caption . '

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'example_approved':
			
			/*$example_q = db_query("SELECT * FROM {xcos_textbook_companion_example} WHERE id = %d LIMIT 1", $params['example_approved']['example_id']);
			$example_data = db_fetch_object($example_q);*/
			$query = db_select('xcos_textbook_companion_example');
			$query->fields('xcos_textbook_companion_example');
			$query->condition('id', $params['example_approved']['example_id']);
			$query->range(0, 1);
			$result = $query->execute();
			$example_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $example_data->chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $chapter_data->preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$user_data = user_load($params['example_approved']['user_id']);
			$message['headers'] = $params['example_approved']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your uploaded example has been approved for Textbook Companion', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

Your example for Xcos Textbook Companion with the following details is approved.

Title of the book: ' . $preference_data->book . '
Title of the chapter: ' . $chapter_data->name . '
Example number: ' . $example_data->number . '
Caption: ' . $example_data->caption . '

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'example_disapproved':
			
			$user_data = user_load($params['example_disapproved']['user_id']);
			$preference_id = $params['example_disapproved']['preference_id'];
			$chapter_id = $params['example_disapproved']['chapter_id'];
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$message['headers'] = $params['example_disapproved']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] Your uploaded example has been disapproved for Textbook Companion', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

Your following example has been disapproved:

Title of the book: ' . $preference_data->book . '
Title of the chapter: ' . $chapter_data->name . '
Example number: ' . $params['example_disapproved']['example_number'] . '
Caption: ' . $params['example_disapproved']['example_caption'] . '

Reason for disapproval: ' . $params['example_disapproved']['message'] . '

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'example_deleted_user':

			$user_data = user_load($params['example_deleted_user']['user_id']);
			//var_dump($user_data);die;
			$preference_id = $params['example_deleted_user']['preference_id'];
			$chapter_id = $params['example_deleted_user']['chapter_id'];
			$query = db_select('xcos_textbook_companion_chapter');
			$query->fields('xcos_textbook_companion_chapter');
			$query->condition('id', $chapter_id);
			$query->range(0, 1);
			$result = $query->execute();
			$chapter_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_preference');
			$query->fields('xcos_textbook_companion_preference');
			$query->condition('id', $preference_id);
			$query->range(0, 1);
			$result = $query->execute();
			$preference_data = $result->fetchObject();
			$query = db_select('xcos_textbook_companion_proposal');
			$query->fields('xcos_textbook_companion_proposal');
			$query->condition('id', $preference_data->proposal_id);
			$query->range(0, 1);
			$result = $query->execute();
			$proposal_data = $result->fetchObject();
			$message['headers'] = $params['example_deleted_user']['headers'];
			$message['subject'] = t('[!site_name] User has deleted pending example for Textbook Companion', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear !user_name,
Your following pending example has been deleted :

Title of the Book: ' . $params['example_deleted_user']['book_title'] . '
Title of the Chapter: ' . $params['example_deleted_user']['chapter_title'] . '
Example number: ' . $params['example_deleted_user']['example_number'] . '
Caption: ' . $params['example_deleted_user']['example_caption'] . '

Best Wishes,

!site_name Team,
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'dependency_uploaded':
			// bcc to xcos_textbook_companion_emails
			$user_data = user_load($params['dependency_uploaded']['user_id']);
			$message['headers'] = $params['dependency_uploaded']['headers'];
			$dependency_files = implode(',', $params['dependency_uploaded']['dependency_names']);
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] You have uploaded dependency file', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear !user_name,

You have uploaded following dependency files:
    ' . $dependency_files . '

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'feedback_received':

			$user_data = user_load($params['feedback_received']['user_id']);
			$message['headers'] = $params['feedback_received']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] We have received your feedback', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We have received your following feedback

Title of the Book: ' . $params['feedback_received']['book_title'] . '
Title of the Chapter: ' . $params['feedback_received']['chapter_number'] . ' ' . $params['feedback_received']['chapter_title'] . '
Example No.: ' . $params['feedback_received']['example_no'] . '

Your feedback :
' . $params['feedback_received']['feedback'] . '

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'internshipform':

			$user_data = user_load($params['internshipform']['user_id']);
			$message['headers'] = $params['internshipform']['headers'];
			$message['subject'] = t('[!site_name] We have received your feedback', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We have received your Internship Form Application for the book 

Title of the Book: ' . $params['internshipform']['book_title'] . '
Title of the Chapter: ' . $params['internshipform']['chapter_number'] . ' ' . $params['internshipform']['chapter_title'] . '
Example No.: ' . $params['internshipform']['example_no'] . '

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'copyrighttransferform':

			$user_data = user_load($params['copyrighttransferform']['user_id']);
			$message['headers'] = $params['copyrighttransferform']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] We have received your feedback', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We have received your Copyright Form Application for the book 

Title of the Book: ' . $params['copyrighttransferform']['book_title'] . '
Title of the Chapter: ' . $params['copyrighttransferform']['chapter_number'] . ' ' . $params['copyrighttransferform']['chapter_title'] . '
Example No.: ' . $params['copyrighttransferform']['example_no'] . '

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'undertakingform':
			$user_data = user_load($params['undertakingform']['user_id']);
			$message['headers'] = $params['undertakingform']['headers'];
			$message['subject'] = t('[!site_name][Xcos Textbook Companion] We have received your feedback', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We have received your Undertaking Form Application for the book 

Title of the Book: ' . $params['undertakingform']['book_title'] . '
Title of the Chapter: ' . $params['undertakingform']['chapter_number'] . ' ' . $params['undertakingform']['chapter_title'] . '
Example No.: ' . $params['undertakingform']['example_no'] . '

Best Wishes,

!site_name Team
FOSSEE, IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'remark':
			$user_data = user_load($params['remark']['user_id']);
			$message['headers'] = $params['remark']['headers'];
			$message['subject'] = t('[!site_name] A remark has been given.Please check your contact detail form', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

A Remark has been given.Please check your Contact Detail Form

Title of the Book: ' . $params['internshipform']['book_title'] . '
Title of the Chapter: ' . $params['internshipform']['chapter_number'] . ' ' . $params['internshipform']['chapter_title'] . '
Example No.: ' . $params['internshipform']['example_no'] . '

Best Wishes,

!site_name Team,
FOSSEE,IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'cheque_sent':

			$user_data = user_load($params['cheque_sent']['user_id']);
			$message['headers'] = $params['cheque_sent']['headers'];
			$message['subject'] = t('[!site_name] We have received your feedback', array(
				'!site_name' => variable_get('site_name', '')
			));
			$message['body'] = array(
				'body' => t('
Dear ' . $proposal_data->full_name . ',

We have Sent Cheque for the following book proposed

Title of the Book: ' . $params['cheque_sent']['book_title'] . '
Title of the Chapter: ' . $params['cheque_sent']['chapter_number'] . ' ' . $params['cheque_sent']['chapter_title'] . '
Example No.: ' . $params['cheque_sent']['example_no'] . '

Best Wishes,

!site_name Team,
FOSSEE,IIT Bombay', array(
					'!site_name' => variable_get('site_name', ''),
					'!user_name' => $user_data->name
				))
			);
			break;
		case 'standard':
			// bcc to xcos_textbook_companion_emails
			$message['headers'] = $params['standard']['headers'];
			$message['subject'] = $params['standard']['subject'];
			$message['body'] = $params['standard']['body'];
			break;
	} //$key
}
/* AJAX CALLS */
function xcos_textbook_companion_ajax()
{
	$query_type = arg(2);
	if ($query_type == 'chapter_title')
	{
		$chapter_number = arg(3);
		$preference_id = arg(4);
		/*$chapter_q = db_query("SELECT * FROM {xcos_textbook_companion_chapter} WHERE number = %d AND preference_id = %d LIMIT 1", $chapter_number, $preference_id);*/
		$query = db_select('xcos_textbook_companion_chapter');
		$query->fields('xcos_textbook_companion_chapter');
		$query->condition('number', $chapter_number);
		$query->condition('preference_id', $preference_id);
		$query->range(0, 1);
		$chapter_q = $query->execute();
		if ($chapter_data = $chapter_q->fetchObject())
		{
			echo $chapter_data->name;
			return;
		} //$chapter_data = $chapter_q->fetchObject()
	} //$query_type == 'chapter_title'
	else if ($query_type == 'example_exists')
	{
		$chapter_number = arg(3);
		$preference_id = arg(4);
		$example_number = arg(5);
		$chapter_id = 0;
		/* $chapter_q = db_query("SELECT * FROM {xcos_textbook_companion_chapter} WHERE number = %d AND preference_id = %d LIMIT 1", $chapter_number, $preference_id);*/
		$query = db_select('xcos_textbook_companion_chapter');
		$query->fields('xcos_textbook_companion_chapter');
		$query->condition('number', $chapter_number);
		$query->condition('preference_id', $preference_id);
		$query->range(0, 1);
		$chapter_q = $query->execute();
		if (!$chapter_data = $chapter_q->fetchObject())
		{
			echo '';
			return;
		} //!$chapter_data = $chapter_q->fetchObject()
		else
		{
			$chapter_id = $chapter_data->id;
		}
		/*$example_q = db_query("SELECT * FROM {xcos_textbook_companion_example} WHERE chapter_id = %d AND number = '%s' LIMIT 1", $chapter_id, $example_number);*/
		$query = db_select('xcos_textbook_companion_example');
		$query->fields('xcos_textbook_companion_example');
		$query->condition('chapter_id', $chapter_id);
		$query->condition('number', $example_number);
		$query->range(0, 1);
		$example_q = $query->execute();
		if ($example_data = $example_q->fetchObject())
		{
			if ($example_data->approval_status == 1)
				echo 'Warning! Example already approved. You cannot upload the same example again.';
			else
				echo 'Warning! Example already uploaded. Delete the example and reupload it.';
			return;
		} //$example_data = $example_q->fetchObject()
	} //$query_type == 'example_exists'
	echo '';
}
/*************************** VALIDATION FUNCTIONS *****************************/
function xcos_textbook_companion_check_valid_filename($file_name)
{
	if (!preg_match('/^[0-9a-zA-Z\_\.]+$/', $file_name))
		return FALSE;
	else if (substr_count($file_name, ".") > 1)
		return FALSE;
	else
		return TRUE;
}
function xcos_checkname($name = '')
{
	if (!preg_match('/^[0-9a-zA-Z\ ]+$/', $name))
		return FALSE;
	else
		return TRUE;
}
function xcos_checkchapter_number($name = '')
{
	if (!preg_match('/^([0-9])+(\.([0-9a-zA-Z])+)+$/', $name))
		return FALSE;
	else
		return TRUE;
}
function xcos_textbook_companion_path()
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'xcos_uploads/tbc_uploads/';
}
function xcos_textbook_companion_temp_path()
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'xcos_uploads/';
}
function xcos_textbook_companion_samplecode_path()
{
	return $_SERVER['DOCUMENT_ROOT'] . base_path() . 'xcos_uploads/tbc_sample_code/';
}
/****************************** DELETION FUNCTIONS ****************************/
function xcos_delete_example($example_id)
{
	global $user;
	$root_path = xcos_textbook_companion_path();
	$status = TRUE;
	/*$example_q = db_query("SELECT * FROM {textbook_companion_example} WHERE id = %d", $example_id);
	$example_data = db_fetch_object($example_q);*/
	$query = db_select('xcos_textbook_companion_example');
	$query->fields('xcos_textbook_companion_example');
	$query->condition('id', $example_id);
	$example_q = $query->execute();
	$example_data = $example_q->fetchObject();
	if (!$example_data)
	{
		drupal_set_message(t('Invalid example.'), 'error');
		return FALSE;
	} //!$example_data
	/*$chapter_q = db_query("SELECT * FROM {textbook_companion_chapter} WHERE id = %d", $example_data->chapter_id);
	$chapter_data = db_fetch_object($chapter_q);*/
	$query = db_select('xcos_textbook_companion_chapter');
	$query->fields('xcos_textbook_companion_chapter');
	$query->condition('id', $example_data->chapter_id);
	$chapter_q = $query->execute();
	$chapter_data = $chapter_q->fetchObject();
	if (!$chapter_data)
	{
		drupal_set_message(t('Invalid example chapter.'), 'error');
		return FALSE;
	} //!$chapter_data
	/* deleting example files */
	/*$examples_files_q = db_query("SELECT * FROM {textbook_companion_example_files} WHERE example_id = %d", $example_id);*/
	$query = db_select('xcos_textbook_companion_example_files');
	$query->fields('xcos_textbook_companion_example_files');
	$query->condition('example_id', $example_id);
	$examples_files_q = $query->execute();
	while ($examples_files_data = $examples_files_q->fetchObject())
	{
		if (!file_exists($root_path . $examples_files_data->filepath))
		{
			$status = FALSE;
			drupal_set_message(t('Error deleting !file. File does not exists.', array(
				'!file' => $examples_files_data->filepath
			)), 'error');
			continue;
		} //!file_exists($root_path . $examples_files_data->filepath)
		/* removing example file */
		if (!drupal_unlink($root_path . $examples_files_data->filepath))
		{
			$status = FALSE;
			drupal_set_message(t('Error deleting !file', array(
				'!file' => $examples_files_data->filepath
			)), 'error');
			/* sending email to admins */
			$email_to = variable_get('xcos_textbook_companion_emails', '');
			$params['standard']['subject'] = "[ERROR] Error deleting example file";
			$params['standard']['body'] = array(
				0 => "Error deleting example files by " . $user->uid . " at " . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . " :
        example id : " . $example_id . "
        file id : " . $examples_files_data->id . "
        file path : " . $examples_files_data->filepath
			);
			if (!drupal_mail('xcos_textbook_companion', 'standard', $email_to, language_default(), $params, variable_get('xcos_textbook_companion_from_email', NULL), TRUE))
				drupal_set_message('Error sending email message.', 'error');
		} //!drupal_unlink($root_path . $examples_files_data->filepath)
		else
		{
			/* deleting example files database entries */
			/*db_query("DELETE FROM {textbook_companion_example_files} WHERE id = %d", $examples_files_data->id);*/
			$query = db_delete('xcos_textbook_companion_example_files');
			$query->condition('id', $examples_files_data->id);
			$num_deleted = $query->execute();
		}
	} //$examples_files_data = $examples_files_q->fetchObject()
	if (!$status)
		return FALSE;
	/* removing example folder */
	$ex_path = $chapter_data->preference_id . '/' . 'CH' . $chapter_data->number . '/' . 'EX' . $example_data->number;
	$dir_path = $root_path . $ex_path;
	if (is_dir($dir_path))
	{
		if (!drupal_rmdir($dir_path))
		{
			drupal_set_message(t('Error deleting folder !folder', array(
				'!folder' => $dir_path
			)), 'error');
			/* sending email to admins */
			$email_to = variable_get('xcos_textbook_companion_emails', '');
			$params['standard']['subject'] = "[ERROR] Error deleting folder";
			$params['standard']['body'] = array(
				0 => "Error deleting folder " . $dir_path . " by " . $user->uid . " at " . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']
			);
			if (!drupal_mail('xcos_textbook_companion', 'standard', $email_to, language_default(), $params, variable_get('xcos_textbook_companion_from_email', NULL), TRUE))
				drupal_set_message('Error sending email message.', 'error');
			return FALSE;
		} //!drupal_rmdir($dir_path)
	} //is_dir($dir_path)
	else
	{
		drupal_set_message(t('Cannot delete example folder. !folder does not exists.', array(
			'!folder' => $dir_path
		)), 'error');
		return FALSE;
	}
	/* deleting example dependency and exmaple database entries */
	/*db_query("DELETE FROM {textbook_companion_example_dependency} WHERE example_id = %d", $example_id);*/
	$query = db_delete('xcos_textbook_companion_example_dependency');
	$query->condition('example_id', $example_id);
	$num_deleted = $query->execute();
	/*db_query("DELETE FROM {textbook_companion_example} WHERE id = %d", $example_id);*/
	$query = db_delete('xcos_textbook_companion_example');
	$query->condition('id', $example_id);
	$num_deleted = $query->execute();
	return $status;
}
function xcos_delete_chapter($chapter_id)
{
	$status = TRUE;
	$root_path = xcos_textbook_companion_path();
	/*$chapter_q = db_query("SELECT * FROM {textbook_companion_chapter} WHERE id = %d", $chapter_id);
	$chapter_data = db_fetch_object($chapter_q);*/
	$query = db_select('xcos_textbook_companion_chapter');
	$query->fields('xcos_textbook_companion_chapter');
	$query->condition('id', $chapter_id);
	$chapter_q = $query->execute();
	$chapter_data = $chapter_q->fetchObject();
	if (!$chapter_data)
	{
		drupal_set_message('Invalid chapter.', 'error');
		return FALSE;
	} //!$chapter_data
	/* deleting examples */
	/*$example_q = db_query("SELECT * FROM {textbook_companion_example} WHERE chapter_id = %d", $chapter_id);*/
	$query = db_select('xcos_textbook_companion_example');
	$query->fields('xcos_textbook_companion_example');
	$query->condition('chapter_id', $chapter_id);
	$example_q = $query->execute();
	while ($example_data = $example_q->fetchObject())
	{
		if (!xcos_delete_example($example_data->id))
			$status = FALSE;
	} //$example_data = $example_q->fetchObject()
	if ($status)
	{
		$dir_path = $root_path . $chapter_data->preference_id . '/CH' . $chapter_data->number;
		if (is_dir($dir_path))
		{
			$res = rmdir($dir_path);
			if (!$res)
			{
				drupal_set_message(t('Error deleting chapter folder !folder', array(
					'!folder' => $dir_path
				)), 'error');
				/* sending email to admins */
				$email_to = variable_get('xcos_textbook_companion_emails', '');
				$params['standard']['subject'] = "[ERROR] Error deleting folder";
				$params['standard']['body'] = "Error deleting folder " . $dir_path;
				if (!drupal_mail('xcos_textbook_companion', 'standard', $email_to, language_default(), $params, variable_get('xcos_textbook_companion_from_email', NULL), TRUE))
					drupal_set_message('Error sending email message.', 'error');
				return FALSE;
			} //!$res
			else
			{
				/* deleting chapter details from database */
				/*db_query("DELETE FROM {textbook_companion_chapter} WHERE id = %d", $chapter_id);*/
				$query = db_delete('xcos_textbook_companion_chapter');
				$query->condition('id', $chapter_id);
				$num_deleted = $query->execute();
				return TRUE;
			}
		} //is_dir($dir_path)
		else
		{
			drupal_set_message(t('Cannot delete chapter folder. !folder does not exists.', array(
				'!folder' => $dir_path
			)), 'error');
			return FALSE;
		}
	} //$status
	return FALSE;
}
function xcos_delete_book($book_id)
{
	$status = TRUE;
	$root_path = xcos_textbook_companion_path();
	/*$preference_q = db_query("SELECT * FROM {textbook_companion_preference} WHERE id = %d", $book_id);
	$preference_data = db_fetch_object($preference_q);*/
	$query = db_select('xcos_textbook_companion_preference');
	$query->fields('xcos_textbook_companion_preference');
	$query->condition('id', $book_id);
	$preference_q = $query->execute();
	$preference_data = $preference_q->fetchObject();
	if (!$preference_data)
	{
		drupal_set_message('Invalid book.', 'error');
		return FALSE;
	} //!$preference_data
	/* delete chapters */
	/*$chapter_q = db_query("SELECT * FROM {textbook_companion_chapter} WHERE preference_id = %d", $preference_data->id);*/
	$query = db_select('xcos_textbook_companion_dependency_files');
		$query->fields('xcos_textbook_companion_dependency_files');
		$query->condition('preference_id', $preference_data->id);
		$result = $query->execute();
		while($row = $result->fetchObject()){
			$root_path = xcos_textbook_companion_path();
			$dest_path = $row->preference_id . '/';
			$dest_path .= 'DEPENDENCIES' . '/';
			unlink($root_path . $dest_path . $row->filename);

			$query = db_delete('xcos_textbook_companion_dependency_files');
			$query->condition('id', $dependency_id);
			$num_deleted = $query->execute();
		}
		$dir_path = $root_path . $preference_data->id . '/DEPENDENCIES/';
		//var_dump($root_path . $preference_data->preference_id);die;
		if (is_dir($dir_path))
		{
			$res = rmdir($dir_path);
		}
	$query = db_select('xcos_textbook_companion_chapter');
	$query->fields('xcos_textbook_companion_chapter');
	$query->condition('preference_id', $preference_data->id);
	$chapter_q = $query->execute();
	while ($chapter_data = $chapter_q->fetchObject())
	{
		if (!xcos_delete_chapter($chapter_data->id))
		{
			$status = FALSE;
		} //!delete_chapter($chapter_data->id)
	} //$chapter_data = $chapter_q->fetchObject()

	return $status;
}
function xcos_delete_file($file_id)
{
	$root_path = xcos_textbook_companion_path();
	/*$file_q = db_query("SELECT * FROM {textbook_companion_example_files} WHERE id = %d LIMIT 1", $file_id);*/
	$query = db_select('xcos_textbook_companion_example_files');
	$query->fields('xcos_textbook_companion_example_files');
	$query->condition('id', $file_id);
	$query->range(0, 1);
	$file_q = $query->execute();
	$file_data = $file_q->fetchObject();
	if (!$file_data)
	{
		drupal_set_message('Invalid file specified.', 'error');
		return FALSE;
	} //!$file_data
	if (!file_exists($root_path . $file_data->filepath))
	{
		drupal_set_message(t('Error deleting !file. File does not exists.', array(
			'!file' => $file_data->filepath
		)), 'error');
		return FALSE;
	} //!file_exists($root_path . $file_data->filepath)
	/* removing example file */
	if (!unlink($root_path . $file_data->filepath))
	{
		drupal_set_message(t('Error deleting !file', array(
			'!file' => $file_data->filepath
		)), 'error');
		/* sending email to admins */
		$email_to = variable_get('xcos_textbook_companion_emails', '');
		$params['standard']['subject'] = "[ERROR] Error deleting file";
		$params['standard']['body'] = "Error deleting file by " . $user->uid . " at " . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . " :
      file id : " . $file_id . "
      file path : " . $file_data->filepath;
		if (!drupal_mail('xcos_textbook_companion', 'standard', $email_to, language_default(), $params, variable_get('xcos_textbook_companion_from_email', NULL), TRUE))
			drupal_set_message('Error sending email message.', 'error');
		return FALSE;
	} //!unlink($root_path . $file_data->filepath)
	else
	{
		/* deleting example files database entries */
		/*db_query("DELETE FROM {textbook_companion_example_files} WHERE id = %d", $file_id);*/
		$query = db_delete('xcos_textbook_companion_example_files');
		$query->condition('id', $file_id);
		$num_deleted = $query->execute();
		return TRUE;
	}
}

function del_xcos_book_pdf($book_id)
{
	$root_path = xcos_textbook_companion_path();
	$dir_path = $root_path . "latex/";
	$query = db_select('xcos_textbook_companion_preference');
	$query->fields('xcos_textbook_companion_preference');
	$query->condition('id', $book_id);
	$query_pre_data = $query->execute();
	$result = $query_pre_data->fetchObject();
	$pdf_filename = "book_" . $result->directory_name . ".pdf";
	if (file_exists($dir_path . $pdf_filename))
		unlink($dir_path . $pdf_filename);
}
function _list_of_software_version()
{
	$software_version = array();
	$query = db_select('r_software_version');
	$query->fields('r_software_version');
	$query->orderBy('r_version', 'ASC');
	$software_version_list = $query->execute();
	while ($software_version_list_data = $software_version_list->fetchObject())
	{
		$software_version[$software_version_list_data->r_version] = $software_version_list_data->r_version;
	} //$software_version_list_data = $software_version_list->fetchObject()
	return $software_version;
}
function _xcos_tbc_list_of_departments()
{
	$department = array();
	$query = db_select('list_of_departments');
	$query->fields('list_of_departments');
	$query->orderBy('id', 'DESC');
	$department_list = $query->execute();
	while ($department_list_data = $department_list->fetchObject())
	{
		$department[$department_list_data->department] = $department_list_data->department;
	} //$department_list_data = $department_list->fetchObject()
	return $department;
}


function _xcos_tbc_list_of_main_categories()
{
	$maincategory = array(
        0 => 'Please select ...'
    );
	//$maincategory = array();
	$query = db_select('list_of_category');
	$query->fields(' list_of_category');
	$query->orderBy('category_id', 'ASC');
	$maincategory_list = $query->execute();
	while ($maincategory_list_data = $maincategory_list->fetchObject())
	{
		$maincategory[$maincategory_list_data->category_id] = $maincategory_list_data->maincategory;
	} //$software_version_list_data = $software_version_list->fetchObject()
	return $maincategory;
}

/*************************************************************************/
/***** Function To convert only first charater of string in uppercase ****/
/*************************************************************************/
function xcos_ucname($string)
{
	$string = ucwords(strtolower($string));
	foreach (array(
		'-',
		'\''
	) as $delimiter)
	{
		if (strpos($string, $delimiter) !== false)
		{
			$string = implode($delimiter, array_map('ucfirst', explode($delimiter, $string)));
		} //strpos($string, $delimiter) !== false
	} //array( '-', '\'' ) as $delimiter
	return $string;
}
function _xcos_dir_name($book, $author, $pref_id)
{
	if (!$pref_id)
	{
		$book_title = xcos_ucname($book);
		$author = xcos_ucname($author);
		$dir_name = $book_title . " " . "by" . " " . $author;
		$directory_name = str_replace("__", "_", preg_replace('/[^a-zA-Z0-9-_]/', "_", $dir_name));
		$query = db_select('xcos_textbook_companion_preference');
		$query->fields('xcos_textbook_companion_preference');
		$query->condition('directory_name', $directory_name);
		$query->condition('approval_status', 1);
		$result = $query->execute()->rowCount();
		if ($result > 0)
		{
			//var_dump('this');die;
			form_set_error('', t('Book is already allotted. Please try another book or contact to administrator'));
			return;
		} //$result > 0
	} //!$pref_id
	else
	{
		$book_title = xcos_ucname($book);
		$author = xcos_ucname($author);
		$dir_name = $book_title . " " . "by" . " " . $author;
		$directory_name = str_replace("__", "_", preg_replace('/[^a-zA-Z0-9-_]/', "_", $dir_name));
		$query = db_select('xcos_textbook_companion_preference');
		$query->fields('xcos_textbook_companion_preference');
		$query->condition('directory_name', $directory_name);
		$query->condition('id', $pref_id);
		$result = $query->execute()->rowCount();
		if ($result > 1)
		{
			form_set_error('', t('Book is already present. Please try another book or contact to administrator'));
			return;
		} //$result > 1
	}
	return $directory_name;
}


function _xcos_tbc_list_of_city_pincode($city=Null, $state=NULL, $district=NULL)
{
	$pincode = array();
	if($city){
		$pincode_list = db_query("SELECT pincode FROM all_india_pincode WHERE city = :city AND state = :state AND district = :district", array(':city' => $city,':state'=> $state, ':district' => $district));
		while ($pincode_list_data = $pincode_list->fetchObject())
		{
			$pincode[$pincode_list_data->pincode] = $pincode_list_data->pincode;
		}
	}
	else{
		$pincode[000000] = '000000';
	}
	return $pincode;
}

function _xcos_tbc_list_of_cities($state=Null, $district=NULL)
{
	$city = array(''=> '- Select -');
	if($state){
		$city_list = db_query("SELECT city FROM all_india_pincode WHERE state = :state AND district = :district ORDER BY city ASC", array(':state'=> $state, ':district' =>$district));
		while ($city_list_data = $city_list->fetchObject())
		{
			$city[$city_list_data->city] = $city_list_data->city;
		}
	}
	return $city;
}

function _xcos_tbc_list_of_district($state=Null)
{
	$district = array(''=> '- Select -');
	if($state){
		$district_list = db_query("SELECT district FROM all_india_pincode WHERE state = :state ORDER BY district ASC", array(':state'=> $state));
		while ($district_list_data = $district_list->fetchObject())
		{
			$district[$district_list_data->district] = $district_list_data->district;
		}
	}
	return $district;
}

function _xcos_tbc_list_of_states()
{
	$states = array(''=> '- Select -');
	$states_list = db_query("SELECT state FROM all_india_pincode WHERE country = 'India' ORDER BY state ASC");
	while ($states_list_data = $states_list->fetchObject())
	{
		$states[$states_list_data->state] = $states_list_data->state;
	}
	return $states;
}

function _xcos_list_of_book_titles()
{
   $existing_tbc_titles = array();
    $result = db_query("SELECT * from list_of_xcos_tbc_titles WHERE {tbc_name} NOT IN( SELECT  CONCAT(book, ' by ', author, ', ', publisher, ', ', year) from xcos_textbook_companion_preference as xtcp JOIN xcos_textbook_companion_proposal as xtcc ON xtcp.proposal_id = xtcc.id WHERE xtcc.proposal_status = 0 OR xtcc.proposal_status = 1 OR xtcc.proposal_status = 3) ORDER BY tbc_name ASC");
    while ($existing_tbc_titles_data = $result->fetchObject()) {
        $existing_tbc_titles[$existing_tbc_titles_data->scilab_tbc_pref_id] = $existing_tbc_titles_data->tbc_name;
    }
    return $existing_tbc_titles;
}

function _list_of_xcos_book_dependency_files()
{
	$book_dependency_files = array();
	$book_dependency_files_class = array();
	/*$book_dependency_files_q = db_query("SELECT * FROM {xcos_textbook_companion_dependency_files} ORDER BY filename ASC");*/
	$query = db_select('xcos_textbook_companion_dependency_files', 'tcdp');
	$query->fields('tcdp');
	$query->fields('tcp', array(
		'book',
		'author',
		'publisher',
		'edition',
		'year'
	));
	$query->leftJoin('xcos_textbook_companion_preference', 'tcp', 'tcdp.preference_id = tcp.id');
	$query->orderBy('tcdp.id', 'DESC');
	$book_dependency_files_q = $query->execute();
	while ($book_dependency_files_data = $book_dependency_files_q->fetchObject())
	{
		$temp_caption = '';
		if ($book_dependency_files_data->caption)
			$temp_caption .= ' ===>[Caption: ' . $book_dependency_files_data->caption . ' ' . ', Book: ' . $book_dependency_files_data->book . ', Author: ' . $book_dependency_files_data->author . ', Publisher: ' . $book_dependency_files_data->publisher . ', Edition: ' . $book_dependency_files_data->edition . ', Year: ' . $book_dependency_files_data->year . ']';
		$book_dependency_files[$book_dependency_files_data->id] = l($book_dependency_files_data->filename, 'xcos-textbook-companion/download/dependency/' . $book_dependency_files_data->id, array(
			'attributes' => array(
				'class' => 'title'
			)
		)) . $temp_caption;
		$book_dependency_files_class[$book_dependency_files_data->id] = $book_dependency_files_data->preference_id;
	} //$book_dependency_files_data = $book_dependency_files_q->fetchObject()
	return array(
		$book_dependency_files,
		$book_dependency_files_class
	);
}